common/models/News.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

namespace common\models;

use yii\db\ActiveRecord;

/**
 * Class News
 * @package common\models
 *
 * @property integer $id
 * @property string $title_en
 * @property string $title_ru
 * @property string $content_en
 * @property string $content_ru
 *
 * @property-read string $title
 * @property-read string $content
 */
class News extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%news}}';
    }

    public function rules()
    {
        return [
            [['title_en', 'title_ru'], 'string', 'min' => 1, 'max' => 255, 'skipOnEmpty' => false],
            [['content_en', 'content_ru'], 'string', 'skipOnEmpty' => false],
        ];
    }

    public function getContent(): string
    {
        $attribute = 'content_'.Lang::getShort();
        return $this->$attribute;
    }

    public function getTitle(): string
    {
        $attribute = 'title_'.Lang::getShort();
        return $this->$attribute;
    }

}

backend/controllers/NewsController.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\{ Controller, ForbiddenHttpException, MethodNotAllowedHttpException, NotFoundHttpException };
use common\models\News;
use backend\models\{ Admin, NewsSearch };


class NewsController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'images-get' => [
                'class' => \vova07\imperavi\actions\GetImagesAction::class,
                'url' => Yii::getAlias('@front_url/images/news/'),
                'path' => '@front_web/images/news/',
            ],
            'image-upload' => [
                'class' => \vova07\imperavi\actions\UploadFileAction::class,
                'url' => Yii::getAlias('@front_url/images/news/'),
                'path' => '@front_web/images/news/',
            ],
            'file-delete' => [
                'class' => \vova07\imperavi\actions\DeleteFileAction::class,
                'url' => Yii::getAlias('@front_url/images/news/'),
                'path' => '@front_web/images/news/',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (!parent::beforeAction($action)) return false;

        /** @var $identity Admin Залогиненый админ */
        $identity = Yii::$app->user->identity;

        if(!$identity->canEditNews)
            throw new ForbiddenHttpException('You do not have rights to do this!');

        return true;
    }

    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', compact('searchModel', 'dataProvider'));
    }

    public function actionEdit($id = 0)
    {
        $id = (int)$id;

        $news = $id > 0 ? News::findOne($id) : new News();
        if (!$news) throw new NotFoundHttpException('News not found!');

        if (Yii::$app->request->isPost)
            if ($news->load(Yii::$app->request->post()) && $news->save())
                return $this->redirect('/news');

        return $this->render('edit', compact('news'));
    }

    public function actionDelete($id)
    {
        if (!Yii::$app->request->isPost)
            throw new MethodNotAllowedHttpException();

        $id = (int)$id;
        $news = $id > 0 ? News::findOne($id) : null;
        if ($news) $news->delete();

        return $this->redirect('/news');
    }

}

backend/views/news/edit.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

use yii\bootstrap\Html;
use kartik\form\ActiveForm;

/* @var $this \yii\web\View */
/* @var $news \common\models\News  */


$this->title = $news->id > 0 ? 'Edit News' : 'Add News';

$this->params['breadcrumbs'][] = ['label' => 'All News', 'url' => '/news'];
$this->params['breadcrumbs'][] = $this->title;

?>
<h1><?= $news->id > 0 ? "{$this->title} '{$news->title_en}'" : $this->title ?></h1>

<div class="row">
    <?php $form = ActiveForm::begin(); ?>

    <div class="col-lg-12">
        <?= $form->field($news, 'title_en')->textInput(['max' => 255, 'required' => true]); ?>

        <?= $form->field($news, 'content_en')->widget(\vova07\imperavi\Widget::class, [
            'settings' => [
                'imageUpload' => '/news/image-upload',
                'imageDelete' => '/news/file-delete',
                'imageManagerJson' => '/news/images-get',
                'plugins' => [ 'fullscreen' ]
            ],
            'plugins' => ['imagemanager' => \vova07\imperavi\bundles\ImageManagerAsset::class,]
        ]); ?>

        <?= $form->field($news, 'title_ru')->textInput(['max' => 255, 'required' => true]); ?>

        <?= $form->field($news, 'content_ru')->widget(\vova07\imperavi\Widget::class, [
            'settings' => [
                'imageUpload' => '/news/image-upload',
                'imageDelete' => '/news/file-delete',
                'imageManagerJson' => '/news/images-get',
                'plugins' => [ 'fullscreen' ]
            ],
            'plugins' => ['imagemanager' => \vova07\imperavi\bundles\ImageManagerAsset::class,]
        ]); ?>

        <div class="form-group text-center">
            <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Cancel', '/news', ['class' => 'btn btn-default']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

backend/views/news/index.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

use yii\bootstrap\Html;
use yii\helpers\Url;
use rmrevin\yii\fontawesome\FAS;
use kartik\grid\{ GridView, ActionColumn };

/* @var $this \yii\web\View */
/* @var $searchModel \backend\models\NewsSearch */
/* @var $dataProvider \yii\data\ActiveDataProvider */


$this->title = 'All News';

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="pull-right">
    <a href="<?= Url::to(['/news/edit']); ?>" class="btn btn-primary">Add News</a>
</div>

<h1><?= $this->title ?></h1>

<div class="row">
    <div class="col-lg-12">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{summary}\n{pager}\n{items}{pager}",
            'export' => false,
            'pager' => [
                'maxButtonCount' => 18,
                'prevPageLabel' => FAS::icon('chevron-left'),
                'nextPageLabel' => FAS::icon('chevron-right'),
                'firstPageLabel' => FAS::icon('chevron-left').FAS::icon('chevron-left'),
                'lastPageLabel' => FAS::icon('chevron-right').FAS::icon('chevron-right'),
            ],
            'columns' => [
                'id',
                'title_en',
                'title_ru',
                [
                    'class' => ActionColumn::class,
                    'template' => '{edit} {delete}',
                    'buttons' => [
                        'edit' => function ($url, $model) {
                            return Html::a(FAS::icon('edit'),
                                Url::to(['/news/edit', 'id' => $model->id]),
                                ['type'=> 'button', 'title'=> 'Edit news', 'class'=>'btn btn-info']);
                        },
                        'delete' => function ($url, $model) {
                            return Html::a(FAS::icon('trash-alt'),
                                Url::to(['/news/delete', 'id' => $model->id]),
                                ['type'=>'button', 'title'=> 'Delete news', 'class'=> 'btn btn-danger',
                                    'data-method' => 'post', 'data-confirm' => 'Are you sure?']);
                        },
                    ],
                ],
            ]
        ]) ?>
    </div>
</div>