common/models/Order.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\{ ActiveQuery, ActiveRecord };


/**
 * Class Order
 * @package common\models
 *
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property string $telephone
 * @property string $email
 * @property integer $pay_method
 * @property string $comment
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Cart[] $carts
 * @property Goods[] $goods
 * @property-read $payMethods
 * @property-read $payMethodsIDs
 * @property-read $statuses
 * @property-read $statusesIDs
 * @property-read integer $created
 * @property-read integer $updated
 */
class Order extends ActiveRecord
{
    public const
        PAY_CARD    = 0,
        PAY_CASH    = 1,
        PAY_PAYPAL  = 2,
        PAY_QIWI    = 3,
        PAY_YANDEX  = 4,
        STATUS_NEW       = 0,
        STATUS_IN_WORK   = 1,
        STATUS_COMPLETED = 2;

    public static function tableName()
    {
        return '{{%order}}';
    }

    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_NEW],
            ['comment', 'default', 'value' => ''],
            [['name', 'address', 'telephone', 'email'], 'string', 'min' => 7, 'max' => 255, 'skipOnEmpty' => false],
            ['pay_method', 'in', 'range' => self::getPayMethodsIDs(), 'skipOnEmpty' => false],
            ['status', 'in', 'range' => self::getStatusesIDs(), 'skipOnEmpty' => false],
            [['comment', 'ip'], 'string', 'min' => 0, 'max' => 255],
            ['email', 'email'],
        ];
    }


    public function behaviors()
    {
        return [
            TimestampBehavior::class,
        ];
    }

    /**
     * @return ActiveQuery|Cart[]
     */
    public function getCarts()
    {
        return $this->hasMany(Cart::class, ['order_id' => 'id']);
    }

    /**
     * @return ActiveQuery|Goods[]
     */
    public function getGoods()
    {
        return $this->hasMany(Goods::class, ['id' => 'goods_id'])
            ->via('carts');
    }

    public static function getPayMethods() : array
    {
        return [
            self::PAY_CARD => Yii::t('msg', 'Credit Card - {types}', ['types' => 'Visa, MasterCard, Maestro, Mir']),
            self::PAY_CASH => Yii::t('msg', 'Cash'),
            self::PAY_PAYPAL => Yii::t('msg', 'PayPal'),
            self::PAY_QIWI => Yii::t('msg', 'Qiwi'),
            self::PAY_YANDEX => Yii::t('msg', 'Yandex.Money'),
        ];
    }

    public static function getPayMethodsIDs()
    {
        return array_keys(self::getPayMethods());
    }

    public static function getStatuses() : array
    {
        return [
            self::STATUS_NEW => 'New',
            self::STATUS_IN_WORK => 'In work',
            self::STATUS_COMPLETED => 'Completed',
        ];
    }

    public static function getStatusesIDs()
    {
        return array_keys(self::getStatuses());
    }

    public function getCreated()
    {
        return date('d/m/Y H:i:s', $this->created_at);
    }

    public function getUpdated()
    {
        return date('d/m/Y H:i:s', $this->updated_at);
    }

}

frontend/models/OrderForm.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */


namespace frontend\models;

use Yii;
use yii\base\Model;
use himiklab\yii2\recaptcha\ReCaptchaValidator;
use common\models\Order;


class OrderForm extends Model
{
    public $name, $address, $telephone, $email, $pay_method, $comment, $reCaptcha;

    public function rules()
    {
        return [
            [['name', 'address', 'telephone', 'email', 'pay_method', 'reCaptcha'], 'required'],
            [['name', 'address', 'email'], 'string', 'min' => 7],
            [['telephone'], 'string', 'min' => 18],
            [['comment'], 'string'],
            ['email', 'email'],
            ['pay_method', 'in', 'range' => Order::getPayMethodsIDs()],
            ['reCaptcha', ReCaptchaValidator::class],
        ];
    }

    public function attributeLabels()
    {
        return [
            'name' => Yii::t('msg', 'Full name'),
            'address' => Yii::t('msg', 'Full address'),
            'telephone' => Yii::t('msg', 'Contact telephone'),
            'pay_method' => Yii::t('msg', 'Payment method'),
            'email' => Yii::t('msg', 'Email'),
            'comment' => Yii::t('msg', 'Comment'),
            'reCaptcha' => Yii::t('msg', 'Bot Check'),
        ];
    }

    public function beforeValidate()
    {
        $this->telephone = str_replace('_', '', $this->telephone);
        return parent::beforeValidate();
    }

}

backend/controllers/OrdersController.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\{ Controller, ForbiddenHttpException, NotFoundHttpException };
use backend\models\{ Admin, OrderSearch };
use common\models\Order;


class OrdersController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (!parent::beforeAction($action)) return false;

        /** @var $identity Admin Залогиненый админ */
        $identity = Yii::$app->user->identity;

        if (!$identity->canEditOrders)
            throw new ForbiddenHttpException('You do not have rights to do this!');

        return true;
    }

    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $status_list = Order::getStatuses();

        return $this->render('index', compact('searchModel', 'dataProvider', 'status_list'));
    }

    public function actionShow($id)
    {
        $id = (int)$id;
        $order = $id > 0 ? Order::findOne($id) : null;
        if (!$order) return new NotFoundHttpException('Order not found!');

        if (Yii::$app->request->isPost) {
            $order->status = Yii::$app->request->post('Order')['status'];
            if ($order->update())
                $this->redirect('/orders');
            else Yii::error(['$order->update failed!', $order->errors, $order->attributes]);
        }

        $status_list = Order::getStatuses();
        $pay_list = Order::getPayMethods();

        $carts = $order->getCarts()
            ->with('goods', 'goods.category', 'goods.category.type')->all();

        return $this->render('show', compact('order', 'status_list', 'pay_list', 'carts'));
    }

}

backend/views/orders/_goods.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

use yii\bootstrap\Html;
use yii\helpers\Url;

/* @var $cart \common\models\Cart */

$goods = $cart->goods;

?>
<tr>
    <td><?= $goods->id ?></td>
    <td><?= $goods->category->type->name ?></td>
    <td><?= $goods->category->name ?></td>
    <td>
        <a href="<?= Url::to(['/goods/edit', 'id' => $goods->id]) ?>">
            <?= $goods->name ?>
        </a>
    </td>
    <td class="img-parent">
        <?= Html::img($goods->imageFullUrl) ?>
    </td>
    <td>$<?= $goods->price ?></td>
    <td><?= $cart->count ?></td>
</tr>

backend/views/orders/index.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

use common\models\Cart;
use common\models\Order;
use yii\bootstrap\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use kartik\grid\{ GridView, ActionColumn };
use rmrevin\yii\fontawesome\FAS;

/* @var $this \yii\web\View */
/* @var $searchModel \backend\models\OrderSearch */
/* @var $dataProvider \yii\data\ActiveDataProvider */
/* @var $status_list array */
/* @var $pay_list array */


$this->title = 'All Orders';

$this->params['breadcrumbs'][] = $this->title;

?>
<h1><?= $this->title ?></h1>

<div class="row">
    <div class="col-lg-12">

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{summary}\n{pager}\n{items}\n{pager}",
            'export' => false,
            'pager' => [
                'maxButtonCount' => 18,
                'prevPageLabel' => FAS::icon('chevron-left'),
                'nextPageLabel' => FAS::icon('chevron-right'),
                'firstPageLabel' => FAS::icon('chevron-left').FAS::icon('chevron-left'),
                'lastPageLabel' => FAS::icon('chevron-right').FAS::icon('chevron-right'),
            ],
            'columns' => [
                [
                    'attribute' => 'id',
                    'width' => '6%',
                ],
                'name',
                'telephone',
                'email',
                [
                    'label' => 'Items',
                    'value' => function ($order) {
                        /* @var $order Order */
                        return array_sum(ArrayHelper::getColumn($order->carts, 'count'));
                    }
                ],
                [
                    'label' => 'Price',
                    'value' => function ($order) {
                        /* @var $order Order */
                        $prices = ArrayHelper::getColumn($order->carts, function ($cart) {
                            /* @var $cart Cart */
                            return $cart->count * $cart->goods->price;
                        });
                        return '$'.array_sum($prices);
                    }
                ],
                [
                    'attribute' => 'status',
                    'format' => 'html',
                    'value' => function ($order) use ($status_list) {
                        switch ($order->status) {
                            case 0: return "<span class=\"label label-danger\">{$status_list[$order->status]}</span>";
                            case 1: return "<span class=\"label label-primary\">{$status_list[$order->status]}</span>";
                            default: return "<span class=\"label label-success\">{$status_list[$order->status]}</span>";
                        }

                    },
                    'filter' => $status_list
                ],
                [
                    'label' => 'Created and Updated',
                    'format' => 'html',
                    'value' => function ($order) {
                        return "<b>C</b>: $order->created<br><b>U</b>: $order->updated";
                    }
                ],
                [
                    'class' => ActionColumn::class,
                    'template' => '{show}',
                    'buttons' => [
                        'show' => function ($url, $order) {
                            return Html::a(FAS::icon('edit'),
                                Url::to(['/orders/show', 'id' => $order->id]), [
                                    'type' => 'button', 'title' => 'Show order', 'class' => 'btn btn-info',
                                ]);
                        },
                    ],
                ],
            ]
        ]) ?>

    </div>
</div>

backend/views/orders/show.php
<?php
/**
 * Copyright (c) 2018
 * Developed by Wixty (wixtys@gmail.com)
 * All rights reserved
 */

use yii\bootstrap\Html;
use kartik\form\ActiveForm;

/* @var $this \yii\web\View */
/* @var $order \common\models\Order  */
/* @var $status_list array */
/* @var $pay_list array */
/* @var $carts \common\models\Cart[] */


$this->title = 'Show Order';

$this->params['breadcrumbs'][] = ['label' => 'All Orders', 'url' => '/orders'];
$this->params['breadcrumbs'][] = $this->title;

?>
<h1><?= "{$this->title} №{$order->id}" ?></h1>

<div class="row">
    <?php $form = ActiveForm::begin() ?>
    <div class="col-lg-3">
        <?= $form->field($order, 'id')->textInput(['readonly' => true]) ?>
        <?= $form->field($order, 'name')->textInput(['readonly' => true]) ?>
        <?= $form->field($order, 'address')->textInput(['readonly' => true]) ?>
    </div>
    <div class="col-lg-3">
        <?= $form->field($order, 'pay_method')->dropDownList($pay_list, ['readonly' => true]) ?>
        <?= $form->field($order, 'telephone')->textInput(['readonly' => true]) ?>
        <?= $form->field($order, 'email')->textInput(['readonly' => true]) ?>
    </div>
    <div class="col-lg-3">
        <?= $form->field($order, 'ip')->textInput(['readonly' => true]) ?>
        <?= $form->field($order, 'created')->textInput(['readonly' => true]) ?>
        <?= $form->field($order, 'updated')->textInput(['readonly' => true]) ?>
    </div>
    <div class="col-lg-3">
        <?= $form->field($order, 'comment')->textarea(['rows' => 2, 'readonly' => true]) ?>
        <?= $form->field($order, 'status')->dropDownList($status_list) ?>
        <div class="form-group text-center">
            <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Cancel', '/orders', ['class' => 'btn btn-default']) ?>
        </div>
    </div>
    <?php ActiveForm::end() ?>

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center bold">Goods in this order</h3>
            </div>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <td>Goods ID</td>
                    <td>Type</td>
                    <td>Category</td>
                    <td>Name</td>
                    <td>Photo</td>
                    <td>Price</td>
                    <td>Count</td>
                </tr>
                </thead>
                <tbody>
                <?php $total_price = $total_count = 0;
                foreach ($carts as $cart) :
                    echo $this->render('_goods', compact('cart'));
                    $total_price += $cart->goods->price * $cart->count;
                    $total_count += $cart->count;
                endforeach; ?>
                </tbody>
                <tfoot class="bold">
                <tr>
                    <td colspan="5" class="table-total">Total</td>
                    <td>$<?= $total_price ?></td>
                    <td><?= $total_count ?></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>

</div>